Repository grafana/agent, pull requests merged in 2022-02, with the labels that each got.

#1301 [dev.frontend-receiver] Add app o11y receiver integration
  CHANGELOG.md
  docs/configuration/integrations/integrations-next/_index.md
  docs/configuration/integrations/integrations-next/app-o11y-exporter.md
  go.mod
  go.sum
  pkg/integrations/install/install.go
  pkg/integrations/v2/app_o11y_receiver/app_o11y_receiver.go
  pkg/integrations/v2/app_o11y_receiver/config/config.go
  pkg/integrations/v2/app_o11y_receiver/config/config_test.go
  pkg/integrations/v2/app_o11y_receiver/exporters/exporter.go
  pkg/integrations/v2/app_o11y_receiver/exporters/loki.go
  pkg/integrations/v2/app_o11y_receiver/exporters/loki_test.go
  pkg/integrations/v2/app_o11y_receiver/handler/handler.go
  pkg/integrations/v2/app_o11y_receiver/handler/handler_test.go
  pkg/integrations/v2/app_o11y_receiver/models/exception.go
  pkg/integrations/v2/app_o11y_receiver/models/log.go
  pkg/integrations/v2/app_o11y_receiver/models/measurement.go
  pkg/integrations/v2/app_o11y_receiver/models/measurement_test.go
  pkg/integrations/v2/app_o11y_receiver/models/meta.go
  pkg/integrations/v2/app_o11y_receiver/models/payload.go
  pkg/integrations/v2/app_o11y_receiver/models/payload_test.go
  pkg/integrations/v2/app_o11y_receiver/models/testdata/payload.json
  pkg/integrations/v2/app_o11y_receiver/tools/ratelimiting/ratelimiter.go
  pkg/integrations/v2/app_o11y_receiver/tools/ratelimiting/ratelimiter_test.go
  pkg/integrations/v2/app_o11y_receiver/utils/keyval.go
Labels: dev-branch

#1330 Add K8s eventhandler integration
  .gitignore
  CHANGELOG.md
  docs/configuration/integrations/integrations-next/_index.md
  docs/configuration/integrations/integrations-next/eventhandler-config.md
  go.sum
  pkg/integrations/install/install.go
  pkg/integrations/v2/eventhandler/eventhandler.go
  pkg/integrations/v2/eventhandler/eventhandler_test.go
  pkg/integrations/v2/eventhandler/integration.go
  pkg/integrations/v2/eventhandler/testdata/eventhandler.cache
Labels: enhancement, subsystem/integrations

#1333 [dev.frontend-receiver] Add API key support to app o11y receiver
  CHANGELOG.md
  docs/configuration/integrations/integrations-next/app-o11y-receiver-config.md
  pkg/integrations/v2/app_o11y_receiver/config/config.go
  pkg/integrations/v2/app_o11y_receiver/handler/handler.go
  pkg/integrations/v2/app_o11y_receiver/handler/handler_test.go
Labels: dev-branch

#1359 [dev.frontend-receiver] app o11y receiver internal metrics
  go.mod
  go.sum
  pkg/integrations/v2/app_o11y_receiver/app_o11y_receiver.go
  pkg/integrations/v2/app_o11y_receiver/exporters/loki.go
  pkg/integrations/v2/app_o11y_receiver/exporters/receiver_metrics.go
  pkg/integrations/v2/app_o11y_receiver/exporters/receiver_metrics_test.go
  pkg/integrations/v2/app_o11y_receiver/handler/handler.go
  pkg/integrations/v2/app_o11y_receiver/handler/handler_test.go
  pkg/integrations/v2/app_o11y_receiver/models/measurement_test.go
  pkg/integrations/v2/app_o11y_receiver/tools/ratelimiting/ratelimiter.go
Labels: dev-branch

#1055 RFC: Design in the open
  .github/workflows/markdown.links.config.json
  .github/workflows/publish.yml
  docs/README.md
  docs/rfcs/0000-template.md
  docs/rfcs/0001-designing-in-the-open.md
  docs/user/README.md
  docs/user/_index.md
  docs/user/api/_index.md
  docs/user/assets/logo_and_name.png
  docs/user/configuration/_index.md
  docs/user/configuration/integrations/_index.md
  docs/user/configuration/integrations/cadvisor-config.md
  docs/user/configuration/integrations/consul-exporter-config.md
  docs/user/configuration/integrations/dnsmasq-exporter-config.md
  docs/user/configuration/integrations/elasticsearch-exporter-config.md
  docs/user/configuration/integrations/github-exporter-config.md
  docs/user/configuration/integrations/integrations-next/_index.md
  docs/user/configuration/integrations/integrations-next/eventhandler-config.md
  docs/user/configuration/integrations/kafka-exporter-config.md
  docs/user/configuration/integrations/memcached-exporter-config.md
  docs/user/configuration/integrations/mongodb_exporter-config.md
  docs/user/configuration/integrations/mysqld-exporter-config.md
  docs/user/configuration/integrations/node-exporter-config.md
  docs/user/configuration/integrations/postgres-exporter-config.md
  docs/user/configuration/integrations/process-exporter-config.md
  docs/user/configuration/integrations/redis-exporter-config.md
  docs/user/configuration/integrations/statsd-exporter-config.md
  docs/user/configuration/integrations/windows-exporter-config.md
  docs/user/configuration/logs-config.md
  docs/user/configuration/metrics-config.md
  docs/user/configuration/server-config.md
  docs/user/configuration/traces-config.md
  docs/user/getting-started/_index.md
  docs/user/getting-started/create-config-file.md
  docs/user/getting-started/install-agent-on-windows.md
  docs/user/operation-guide/_index.md
  docs/user/operator/_index.md
  docs/user/operator/add-custom-scrape-jobs.md
  docs/user/operator/architecture.md
  docs/user/operator/custom-resource-quickstart.md
  docs/user/operator/getting-started.md
  docs/user/operator/helm-getting-started.md
  docs/user/scraping-service/_index.md
  docs/user/upgrade-guide/_index.md
  production/README.md
Labels: proposal

#1248 Add option for Operator to pass arguments to GrafanaAgent #1227
  CHANGELOG.md
  pkg/operator/apis/monitoring/v1alpha1/types.go
  pkg/operator/resources_metrics.go
  production/operator/crds/monitoring.grafana.com_grafanaagents.yaml
Labels: operator

#1399 [dev.frontend-receiver] sourcemap support
  docs/configuration/integrations/integrations-next/app-o11y-receiver-config.md
  go.mod
  go.sum
  pkg/integrations/v2/app_o11y_receiver/app_o11y_receiver.go
  pkg/integrations/v2/app_o11y_receiver/config/config.go
  pkg/integrations/v2/app_o11y_receiver/exporters/loki.go
  pkg/integrations/v2/app_o11y_receiver/exporters/loki_test.go
  pkg/integrations/v2/app_o11y_receiver/exporters/receiver_metrics.go
  pkg/integrations/v2/app_o11y_receiver/handler/handler.go
  pkg/integrations/v2/app_o11y_receiver/handler/handler_test.go
  pkg/integrations/v2/app_o11y_receiver/models/exception.go
  pkg/integrations/v2/app_o11y_receiver/sourcemaps/sourcemaps.go
  pkg/integrations/v2/app_o11y_receiver/sourcemaps/sourcemaps_test.go
  pkg/integrations/v2/app_o11y_receiver/sourcemaps/testdata/foo.js
  pkg/integrations/v2/app_o11y_receiver/sourcemaps/testdata/foo.js.map
  pkg/integrations/v2/app_o11y_receiver/utils/consts.go
  pkg/integrations/v2/app_o11y_receiver/utils/origin.go
  pkg/integrations/v2/app_o11y_receiver/utils/origin_test.go
Labels: dev-branch

#1293 cadvisor config Fixes #1281
  pkg/integrations/cadvisor/cadvisor.go
  pkg/integrations/cadvisor/cadvisor_test.go
  pkg/integrations/cadvisor/common.go
  pkg/integrations/integration.go
  pkg/integrations/v2/integrations.go
Labels: subsystem/integrations
