Repository grafana/agent, pull requests merged in 2023-04, with the labels that each got.

#3478 Correct the description of the "Blocks" example
  docs/sources/flow/concepts/configuration_language.md
Labels: backport release-v0.32

#3622 misc: update release note to link to new documentation
  tools/release-note.md
Labels: backport release-v0.33

#3628 Remove symbolic links to old binary names
  CHANGELOG.md
  cmd/grafana-agent-operator/Dockerfile
  cmd/grafana-agent/Dockerfile
  cmd/grafana-agentctl/Dockerfile
  docs/sources/flow/upgrade-guide.md
  docs/sources/operator/upgrade-guide.md
  docs/sources/static/upgrade-guide.md
Labels: backport release-v0.33

#3687 [release-v0.27] Prefer relative aliases
  docs/sources/README.md
  docs/sources/_index.md
  docs/sources/api/_index.md
  docs/sources/configuration/_index.md
  docs/sources/configuration/create-config-file.md
  docs/sources/configuration/dynamic-config.md
  docs/sources/configuration/flags.md
  docs/sources/configuration/integrations/_index.md
  docs/sources/configuration/integrations/apache-exporter-config.md
  docs/sources/configuration/integrations/cadvisor-config.md
  docs/sources/configuration/integrations/consul-exporter-config.md
  docs/sources/configuration/integrations/dnsmasq-exporter-config.md
  docs/sources/configuration/integrations/ebpf-config.md
  docs/sources/configuration/integrations/elasticsearch-exporter-config.md
  docs/sources/configuration/integrations/github-exporter-config.md
  docs/sources/configuration/integrations/integrations-next/_index.md
  docs/sources/configuration/integrations/integrations-next/app-agent-receiver-config.md
  docs/sources/configuration/integrations/integrations-next/eventhandler-config.md
  docs/sources/configuration/integrations/integrations-next/snmp-config.md
  docs/sources/configuration/integrations/integrations-next/vsphere-config.md
  docs/sources/configuration/integrations/kafka-exporter-config.md
  docs/sources/configuration/integrations/memcached-exporter-config.md
  docs/sources/configuration/integrations/mongodb_exporter-config.md
  docs/sources/configuration/integrations/mysqld-exporter-config.md
  docs/sources/configuration/integrations/node-exporter-config.md
  docs/sources/configuration/integrations/postgres-exporter-config.md
  docs/sources/configuration/integrations/process-exporter-config.md
  docs/sources/configuration/integrations/redis-exporter-config.md
  docs/sources/configuration/integrations/snmp-config.md
  docs/sources/configuration/integrations/statsd-exporter-config.md
  docs/sources/configuration/integrations/windows-exporter-config.md
  docs/sources/configuration/logs-config.md
  docs/sources/configuration/metrics-config.md
  docs/sources/configuration/scraping-service.md
  docs/sources/configuration/server-config.md
  docs/sources/configuration/traces-config.md
  docs/sources/cookbook/_index.md
  docs/sources/cookbook/dynamic-configuration/01_Basics/01_Structure.md
  docs/sources/cookbook/dynamic-configuration/01_Basics/02_Instances.md
  docs/sources/cookbook/dynamic-configuration/01_Basics/03_Integrations.md
  docs/sources/cookbook/dynamic-configuration/01_Basics/04_Logs_and_Traces.md
  docs/sources/cookbook/dynamic-configuration/02_Templates/01_Looping.md
  docs/sources/cookbook/dynamic-configuration/02_Templates/02_Datasources.md
  docs/sources/cookbook/dynamic-configuration/02_Templates/03_Datasource_and_Objects.md
  docs/sources/cookbook/dynamic-configuration/03_Advanced_Datasources/01_AWS.md
  docs/sources/cookbook/dynamic-configuration/_index.md
  docs/sources/operation-guide/_index.md
  docs/sources/operator/_index.md
  docs/sources/operator/add-custom-scrape-jobs.md
  docs/sources/operator/architecture.md
  docs/sources/operator/custom-resource-quickstart.md
  docs/sources/operator/getting-started.md
  docs/sources/operator/helm-getting-started.md
  docs/sources/set-up/_index.md
  docs/sources/set-up/install-agent-binary.md
  docs/sources/set-up/install-agent-docker.md
  docs/sources/set-up/install-agent-macos.md
  docs/sources/set-up/install-agent-on-windows.md
  docs/sources/set-up/quick-starts.md
  docs/sources/upgrade-guide/_index.md
Labels: backport

#3691 [release-v0.25] Prefer relative aliases
  docs/user/README.md
  docs/user/_index.md
  docs/user/api/_index.md
  docs/user/configuration/_index.md
  docs/user/configuration/create-config-file.md
  docs/user/configuration/dynamic-config.md
  docs/user/configuration/flags.md
  docs/user/configuration/integrations/_index.md
  docs/user/configuration/integrations/cadvisor-config.md
  docs/user/configuration/integrations/consul-exporter-config.md
  docs/user/configuration/integrations/dnsmasq-exporter-config.md
  docs/user/configuration/integrations/elasticsearch-exporter-config.md
  docs/user/configuration/integrations/github-exporter-config.md
  docs/user/configuration/integrations/integrations-next/_index.md
  docs/user/configuration/integrations/integrations-next/app-agent-receiver-config.md
  docs/user/configuration/integrations/integrations-next/eventhandler-config.md
  docs/user/configuration/integrations/integrations-next/snmp-config.md
  docs/user/configuration/integrations/kafka-exporter-config.md
  docs/user/configuration/integrations/memcached-exporter-config.md
  docs/user/configuration/integrations/mongodb_exporter-config.md
  docs/user/configuration/integrations/mysqld-exporter-config.md
  docs/user/configuration/integrations/node-exporter-config.md
  docs/user/configuration/integrations/postgres-exporter-config.md
  docs/user/configuration/integrations/process-exporter-config.md
  docs/user/configuration/integrations/redis-exporter-config.md
  docs/user/configuration/integrations/snmp-config.md
  docs/user/configuration/integrations/statsd-exporter-config.md
  docs/user/configuration/integrations/windows-exporter-config.md
  docs/user/configuration/logs-config.md
  docs/user/configuration/metrics-config.md
  docs/user/configuration/scraping-service.md
  docs/user/configuration/server-config.md
  docs/user/configuration/traces-config.md
  docs/user/cookbook/_index.md
  docs/user/cookbook/dynamic-configuration/01_Basics/01_Structure.md
  docs/user/cookbook/dynamic-configuration/01_Basics/02_Instances.md
  docs/user/cookbook/dynamic-configuration/01_Basics/03_Integrations.md
  docs/user/cookbook/dynamic-configuration/01_Basics/04_Logs_and_Traces.md
  docs/user/cookbook/dynamic-configuration/02_Templates/01_Looping.md
  docs/user/cookbook/dynamic-configuration/02_Templates/02_Datasources.md
  docs/user/cookbook/dynamic-configuration/02_Templates/03_Datasource_and_Objects.md
  docs/user/cookbook/dynamic-configuration/03_Advanced_Datasources/01_AWS.md
  docs/user/cookbook/dynamic-configuration/_index.md
  docs/user/operation-guide/_index.md
  docs/user/operator/_index.md
  docs/user/operator/add-custom-scrape-jobs.md
  docs/user/operator/architecture.md
  docs/user/operator/custom-resource-quickstart.md
  docs/user/operator/getting-started.md
  docs/user/operator/helm-getting-started.md
  docs/user/set-up/_index.md
  docs/user/set-up/install-agent-binary.md
  docs/user/set-up/install-agent-docker.md
  docs/user/set-up/install-agent-macos.md
  docs/user/set-up/install-agent-on-windows.md
  docs/user/set-up/quick-starts.md
  docs/user/upgrade-guide/_index.md
Labels: backport

#3710 List backspace escape sequence in the documentation
  docs/sources/flow/config-language/expressions/types_and_values.md
Labels: backport release-v0.32, backport release-v0.31, backport release-v0.30, backport release-v0.29, backport release-v0.28, backport release-v0.33
