Repository grafana/agent, pull requests merged in 2023-03, with the labels that each got.

#3274 [release-v0.28] Avoid ambiguous relref lookups by forcing relative resolution
  docs/sources/flow/tutorials/collecting-prometheus-metrics.md
  docs/sources/flow/tutorials/filtering-metrics.md
Labels: type/docs, backport

#3276 Fix typo in Flow string escape sequence
  docs/sources/flow/config-language/expressions/types_and_values.md
Labels: backport release-v0.32, backport release-v0.31, backport release-v0.30, backport release-v0.29, backport release-v0.28

#3315 docs: fix existing references to old binary names
  docs/developer/contributing.md
  docs/sources/flow/monitoring/component_metrics.md
  docs/sources/flow/monitoring/controller_metrics.md
  docs/sources/flow/monitoring/debugging.md
  docs/sources/flow/reference/cli/_index.md
  docs/sources/flow/reference/cli/run.md
  docs/sources/flow/tutorials/collecting-prometheus-metrics.md
Labels: backport release-v0.32, backport release-v0.31

#3316 docs: clarify objects, fmt based on feedback in #3304
  docs/sources/flow/config-language/expressions/types_and_values.md
  docs/sources/flow/config-language/syntax.md
  docs/sources/flow/reference/cli/fmt.md
Labels: backport release-v0.32, backport release-v0.31, backport release-v0.30, backport release-v0.29, backport release-v0.28

#3352 Update prometheus.exporter.unix.md
  docs/sources/flow/reference/components/prometheus.exporter.unix.md
Labels: backport release-v0.32

#3347 Update local.file.md
  docs/sources/flow/reference/components/local.file.md
Labels: type/docs, backport release-v0.32, backport release-v0.31, backport release-v0.30, backport release-v0.29, backport release-v0.28
