Repository grafana/agent, pull requests merged in 2024-09, with the labels that each got.

#6896 Backport controller refs order wiring
  CHANGELOG.md
  internal/flow/declare_test.go
  internal/flow/internal/controller/component_references.go
Labels: needs-attention

#6906 fix: close procRoot dir
  internal/component/pyroscope/java/asprof/asprof.go
Labels: needs-attention

#6878 Backport: nest datapath in parents to prevent collision in nested import.git
  CHANGELOG.md
  internal/flow/internal/controller/node_config_import.go
Labels: needs-attention

#6897 backport container restart support in loki source
  CHANGELOG.md
  internal/component/loki/source/docker/docker.go
  internal/component/loki/source/docker/docker_test.go
  internal/component/loki/source/docker/internal/dockertarget/target.go
  internal/component/loki/source/docker/runner.go
Labels: needs-attention

#6665 agentseed: make sure we have a valid uid, or regenerate
  internal/agentseed/agentseed.go
Labels: bug, needs-attention, variant/static, variant/operator, variant/flow

#6989 Update links in release docs to example PRs
  docs/developer/release/3-update-version-in-code.md
Labels: needs-attention

#7034 Fix up some broken links to Loki
  docs/sources/static/configuration/logs-config.md
Labels: type/docs, backport release-v0.41, backport release-v0.42, backport release-v0.43
